language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.2.0beta1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script:
  - lua -lluacov specs/tests.lua
  
after_success:
  - luacov-coveralls -e framework

notifications:
  email:
    on_success: change
    on_failure: always
